import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import WalletConnectProvider from "@/config/WalletConnectProvider";

import { type Metadata } from "next";
import { Press_Start_2P } from "next/font/google";

const pressStart2P = Press_Start_2P({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-press-start-2p",
});

import { Header } from "./_components/header";

import { headers } from "next/headers";

import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "DEGEN | MEME Launchpad on Pulsechain",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const cookies = headersList.get("cookie");

  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${pressStart2P.variable}`}
    >
      <body className="bg-degen-white font-sans">
        <WalletConnectProvider cookies={cookies}>
          <NuqsAdapter>
            <Header />
            {children}
          </NuqsAdapter>
        </WalletConnectProvider>
      </body>
    </html>
  );
}
